services:
  - type: web
    name: news-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.8.12"
    autoDeploy: true
    healthCheckPath: /
    region: oregon
    plan: free
    numInstances: 1
    runtime: python